name: Continuos Integration with GitHub
on:

  push:

    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 22
      uses: actions/setup-java@v3

      with:
        java-version: 22
        distribution: temurin
    - name: clean project
      run: chmod +x ./gradlew && ./gradlew clean
    - name: run all test
      run: ./gradlew testClasses
    - name: create .jar and install
      run: ./gradlew bootJar